= pasokey.net

この README は https://pasokey.net[pasokey.net] の概要紹介・利用規約・プライバシーポリシーを兼ねています．

CAUTION: できるだけ短く簡潔になるようにしています．「登録するならこれぐらい読んでね」ということです．

== pasokey.net について

https://pasokey.net[pasokey.net]（以下『当サーバー』とします）は，
サークル『 https://pasokonistan.github.io[パソコニスタン] 』（以下，『管理者』とします）によって，趣味で運用・提供される https://github.com/misskey-dev/misskey[Misskey] サーバーです．

== 運用に関する情報

- メンテナンス情報など: https://github.com/pasokonistan/pasokey.net/issues[GitHub Issues]
- status page: https://stats.uptimerobot.com/QLk7XC6Kxv/793928285[UptimeRobot]

== おことわり
- 当サーバーによるサービスは無償かつ *無保証* にて提供されます
- 管理者は予告なく一時的なサービス停止を伴うメンテナンスを行うことがあります
- 管理者は当サーバーで発生したユーザ間のトラブルや不利益について責任を負いません
- Not for me だなと思ったら，他のサーバーに行くなり，自分でサーバーを立てるなりしましょう
- 当サーバーでの投稿などをインターネット上から完全に削除することはほとんど不可能と思ってください

NOTE: ActivityPub で相互に接続するという意味では，Mastodon などの別の実装もあります．もちろん自分で実装してもいいんですよ．

CAUTION: ActivityPub を使用しているため，一度外部に配信された投稿などは，当サーバーで削除しても，他のサーバー・ActivityPub 実装において適切に削除されるとは限りません．これはインターネットにおける一般的な話でもあります．

== 本文書の更新について

本文書は https://github.com/pasokonistan/pasokey.net[Git リポジトリ] で管理されています．
有効なものは https://github.com/pasokonistan/pasokey.net/blob/pasokey/README.adoc[default branch にあるもの] です．
管理者は default branch では基本的に force push は行わないものとします．
そのため，変更履歴は `git blame` などで容易に参照可能です．

TIP: 当サーバーや本文書に関する疑問や要望は 本リポジトリの Issues で受け付けています．不足している点の Pull Request での修正も歓迎です．ただし，確実な対応を保証するものではありません．

== 当サーバーのルール

基本的に自由です．

ただし，下記項目に該当する行為は，サイレンス処置・凍結・アカウント削除などの対象となる場合があります．

- 管理者の許可なく，サーバーに対して意図的に負荷をかける行為
- 日本の法令に反する行為
その他，管理者が不適切と判断する行為

== プライバシーポリシー

=== 収集する情報

- ユーザ名，メールアドレス，パスワードなど，基本的なアカウント情報
- ユーザの投稿やリアクション，フォローなど，ユーザの活動として保存される情報
- IPアドレスやその他メタデータ

=== 情報を収集・利用する目的

- Misskey の機能の提供
- アカウント登録のための確認，お知らせの配信
- 当インスタンスの運用やその改善のため
  - モデレーション

=== プライバシーポリシーの変更

- 本ポリシーの内容はユーザに通知することなく変更されることがあります
